spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: ${PORT:8443}
  ssl:
    enabled: ${SERVER_SSL_ENABLED:true}
    key-store: ${SERVER_SSL_KEY_STORE:file:/app/keystore.p12}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD:changeit}
    key-store-type: ${SERVER_SSL_KEY_STORE_TYPE:PKCS12}
    key-alias: ${SERVER_SSL_KEY_ALIAS:ems-backend}

logging:
  level:
    com.ems: INFO
    org.springframework.security: WARN
